development:
  adapter: mysql
  encoding: utf8
  database: development
  username: robert@localhost
  password: mypass
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  database: db/test.mysql2
  username: robert@localhost
  password: mypass
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  database: db/production.mysql2
  username: robert@localhost
  password: mypass
  host: localhost

gem 'mysql2'
