development:
  adapter: mysql2
  encoding: utf8
  database: development
  username: robert
  password: mypass
  host: 127.0.0.1

test:
  adapter: mysql2
  encoding: utf8
  database: app7912272
  username: app7912272
  password: mypass
  host: instance27464.db.xeround.com.
  port: 16304

production:
  adapter: mysql2
  encoding: utf8
  database: app7912272
  username: app7912272
  password: mypass
  host:  instance27464.db.xeround.com.
  port: 16304
